export enum EntityName {
	Otp = "otp",
	User = "user",
	Books = "books",
	Writer = "writer",
	Editor = "editor",
	Basket = "basket",
	Profile = "profile",
	Category = "category",
	Discount = "discount",
	Publisher = "publisher",
	Translator = "translator",
	BookComment = "book_comment",
	BookBookmark = "book_bookmarks",
	BookCommentLike = "book_comment_like",
}
