export enum EntityName {
	Otp = "otp",
	User = "user",
	Books = "books",
	Writer = "writer",
	Editor = "editor",
	Basket = "basket",
	Comment = "comment",
	Profile = "profile",
	Category = "category",
	Discount = "discount",
	Publisher = "publisher",
	Translator = "translator",
	ImagesBook = "book_images",
	CommentLike = "comment_like",
	BookWriters = "book_writers",
	BookEditors = "Book_editors",
	BookBookmark = "book_bookmarks",
	BookCategorys = "Book_categorys",
	BookPublishers = "Book_publishers",
	BookTranslators = "Book_translators",
}
